# Generated by Django 3.2.9 on 2021-12-12 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosyaAdi', models.CharField(max_length=100, null=True)),
                ('yazarAdi', models.CharField(max_length=100, null=True)),
                ('numara', models.CharField(max_length=100, null=True)),
                ('dersAdi', models.CharField(max_length=100, null=True)),
                ('juriler', models.CharField(max_length=100, null=True)),
                ('donem', models.CharField(max_length=100, null=True)),
                ('ozet', models.CharField(max_length=500, null=True)),
                ('anahtarKelimeler', models.CharField(max_length=100, null=True)),
                ('baslik', models.CharField(max_length=100, null=True)),
                ('ogretim', models.CharField(max_length=100, null=True)),
                ('pdf', models.FileField(null=True, upload_to='files/pdfs/')),
                ('danisman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
