# Generated by Django 3.2.9 on 2021-12-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='danisman',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
