# Generated by Django 3.2.9 on 2021-12-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_file_donem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dosyaAdi',
        ),
    ]
