# Generated by Django 3.2.9 on 2021-12-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_file_dosyaadi'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='donem',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
