# Generated by Django 3.2.9 on 2021-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_file_donem'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hocaID',
            field=models.IntegerField(null=True),
        ),
    ]
