# Generated by Django 3.2.9 on 2021-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_file_hocaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ozet',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
